run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - gosec
    - prealloc
    - misspell
    - noctx
    - bodyclose
    - durationcheck
    - nilerr
    - exhaustive
    - copyloopvar

linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam

  gosec:
    excludes:
      - G104 # unhandled errors on deferred Close
      - G114 # http.ListenAndServe without timeout

  exhaustive:
    default-signifies-exhaustive: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-dirs:
    - vendor
